# Generated by Django 4.1.3 on 2022-11-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_users_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
